pentaho_script_file:
    class: File
    path: load_csv_to_db.ktr 
pentaho_logging_level: /level:Detailed
pentaho_logfile_location: /logfile:logger.log
d2r_base_uri: http://johanvansoest.nl/rdf/testCwl/
d2r_mapping_file:
    class: File
    path: registry_mapping.ttl
verbose: true
