version: "2"
services:
  postgres:
    image: postgres
    volumes:
      - ../mapping-validator/workflows/psql_init/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=postgres
  cwl_runner:
    build:
      context: cwl_runner
    volumes:
      - ../clinical-data-workflow/workflows/data/:/data/
    links:
      - postgres:postgresdb
  virtuoso:
    build:
      context: docker-virtuoso
    ports:
      - "1111:1111"
      - "8890:8890"
    links:
      - postgres:postgresdb
