version: "3"
services:
  postgres:
    image: postgres
    volumes:
      - ../mapping-validator/workflows/psql_init/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "2345:5432"
  cwl_runner:
    build:
      context: cwl_runner
    volumes:
      - ../clinical-data-workflow/workflows/data/:/data/
    links:
      - postgres:postgresdb
