version: "2"
services:
  postgres:
    image: postgres
    volumes:
      - ../clinical-data-workflow/workflows/psql_init/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "2345:5432"
  cwl_runner:
    build:
      context: cwl_runner
    volumes:
      - ../clinical-data-workflow/workflows/data/:/data/
    links:
      - postgres:postgresdb
  virtuoso:
    build:
      context: docker-virtuoso
    volumes:
      - ../clinical-data-workflow/workflows/data/:/import/data/
    ports:
      - "1111:1111"
      - "8890:8890"
    links:
      - postgres:postgresdb
  garlic:
    build:
      context: garlic
    ports:
      - "8888:8888"
      - "8088:8088"
    volumes:
      - ./garlic:/queries/
    links:
      - postgres:postgresdb
      - virtuoso:sparql_endpoint
      - graphdb:sparql_open
  graphdb:
    image: jvsoest/graphdb-free:8.4.1
    ports: 
      - "7200:7200"
    volumes:
      - ./graphdb_template/:/opt/graphdb/home/
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  192.169.230.1/24
