version: "2"
services:
  postgres:
    image: postgres
    volumes:
      - ../clinical-data-workflow/workflows/psql_init/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "2345:5432"
  r2rml:
    image: jvsoest/r2rml
    links:
      - postgres:dbhost
      - graphdb:graphdb
  garlic:
    build:
      context: garlic
    ports:
      - "8888:8888"
      - "8088:8088"
    volumes:
      - ./notebooks:/queries/
    links:
      - postgres:postgresdb
      - graphdb:graphdb
  graphdb:
    image: jvsoest/graphdb-free:fairstation
    ports: 
      - "7200:7200"
    # volumes:
    #   - ./graphdb_template/:/opt/graphdb/home/
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  192.169.230.1/24
