version: "2"
services:
  slapd:
    image: dcm4che/slapd-dcm4chee:2.4.40-8.1
    ports:
      - "389:389"
    env_file: docker-compose.env
#    volumes:
#      - /etc/timezone:/etc/timezone
#      - /etc/localtime:/etc/localtime
#      - /var/local/dcm4chee-arc/ldap:/var/lib/ldap
#      - /var/local/dcm4chee-arc/slapd.d:/etc/ldap/slapd.d
  postgres:
    image: dcm4che/postgres-dcm4chee:9.6-8
    ports:
      - "5432:5432"
    env_file: docker-compose.env
    # volumes:
    #     - /etc/timezone:/etc/timezone
    #     - /etc/localtime:/etc/localtime
    #     - /var/local/dcm4chee-arc/db:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch:2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    # volumes:
    #   - /etc/timezone:/etc/timezone
    #   - /etc/localtime:/etc/localtime
    #   - /var/local/dcm4chee-arc/elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: kibana:4.6
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
    # volumes:
    #   - /etc/timezone:/etc/timezone
    #   - /etc/localtime:/etc/localtime
  logstash:
    image: dcm4che/logstash-dcm4chee:2.4-0
    ports:
      - "12201:12201/udp"
      - "8514:8514/udp"
      - "8514:8514"
    links:
      - elasticsearch:elasticsearch
    # volumes:
    #   - /etc/timezone:/etc/timezone
    #   - /etc/localtime:/etc/localtime
  dcm4chee-arc:
    image: dcm4che/dcm4chee-arc-psql:5.8.1-logstash-secure-ui
    ports:
      - "8080:8080"
      - "9990:9990"
      - "11112:11112"
      - "2575:2575"
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432 logstash:8514
      AUTH_SERVER_URL: /auth
      JAVA_OPTS: "-Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true"
    links:
      - slapd:ldap
      - postgres:db
      - logstash:logstash
#    volumes:
#      - /etc/timezone:/etc/timezone
#      - /etc/localtime:/etc/localtime
#      - /var/local/dcm4chee-arc/storage:/storage
#      - /var/local/dcm4chee-arc/wildfly:/opt/wildfly/standalone
#  ctp:
#    image: datafairifier/dcd
#    ports:
#      - "389:389"